server:
  port: 8081


spring:

  datasource:
#    connectionProperties=useUnicode=true;characterEncoding=utf-8;:
    #    url: jdbc:mysql://localhost:3306/penguin?useSSL=true
    url: jdbc:mysql://localhost:3306/penguin?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver





    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: sql
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none
    connection:
      characterEncoding: utf-8
      CharSet: utf-8
      useUnicode: true
  jackson:
    serialization:
      INDENT_OUTPUT: true

#
check-user-scopes: true
